# Generated by Django 4.1 on 2022-08-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_pelicula', models.CharField(max_length=100)),
                ('Año_de_estreno', models.IntegerField(max_length=4)),
                ('Descripcion', models.TextField(help_text='Escribir descripción de la película')),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_apellido', models.CharField(max_length=100)),
                ('Año_de_nacimiento', models.IntegerField(max_length=4)),
                ('Peliculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cine.peliculas')),
            ],
        ),
    ]
