# Generated by Django 4.1 on 2022-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cine', '0002_alter_directores_año_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directores',
            name='Peliculas',
        ),
        migrations.AddField(
            model_name='directores',
            name='Peliculas',
            field=models.ManyToManyField(to='Cine.peliculas'),
        ),
    ]
